name: OpenWrt ImageBuilder for CR6608

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download ImageBuilder
      run: |
        # يمكنك استبدال الرابط بالإصدار الذي تريده (مثلاً 23.05.6)
        # هذا الرابط يجب أن يكون دقيقًا لـ ramips/mt7621
        wget https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt7621/openwrt-imagebuilder-23.05.3-ramips-mt7621.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-*.tar.xz
        
    - name: Run Build Script and Apply Customizations
      run: |
        # ندخل إلى مجلد ImageBuilder (قد تحتاج لتعديل الاسم)
        # ونستخدم نفس أمر البناء الذي اتفقنا عليه
        BUILDER_DIR=$(find . -maxdepth 1 -type d -name "openwrt-imagebuilder-*" | head -n 1)
        cd $BUILDER_DIR

        # تنفيذ أمر البناء
        make image PROFILE="xiaomi_mi-router-cr6608" \
        PACKAGES="luci luci-theme-argon -ppp -ppp-mod-pppoe" \
        FILES="../files/"
        # نستخدم ../../files/ لأن مجلد files/ الخاص بنا سيكون في المجلد الأب مرتين

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-custom-firmware
        path: ${{ env.BUILDER_DIR }}/bin/targets/ramips/mt7621/*.bin

